layout = "tile"

[[item]]
title = "Apple iPad"
subtitle = "9th Generation"

[[item]]
title = "New Nintendo 2DS XL"
subtitle = "Black + Lime"

[[item]]
title = "Sony PlayStation 4"
subtitle = "Fat"

[[item]]
title = "Apple iPhone 4s"
subtitle = "Downgraded to iOS 6"
