layout = "tile"

[[item]]
title = "GNOME"
subtitle = "A commiter in Polish team"
link = "https://l10n.gnome.org/teams/pl/"
image = "https://l10n.gnome.org/static/img/favicon.ico"
rotate = true

[[item]]
title = "KDE"
subtitle = "Few contributions, trying to improve quality"
link = "https://l10n.kde.org/team-infos.php?teamcode=pl"
image = "https://kde.org/stuff/clipart/logo/kde-logo-white-blue-rounded-source.svg"
rotate = true
